const results = [
	{
		destinationIata: "MAD",
		price: "91.22",
		currency: "EUR",
		countryCode: "ES",
		flag_link: "https://www.countryflags.io/ES/flat/64.png",
		countryName: "Spain",
		cases: 3636453,
		contaminationRate: 0.0013,
	},
	{
		destinationIata: "SAW",
		price: "107.75",
		currency: "EUR",
		countryCode: "TR",
		flag_link: "https://www.countryflags.io/TR/flat/64.png",
		countryName: "Turkey",
		cases: 5169951,
		contaminationRate: 0.0018,
	},
	{
		destinationIata: "AMS",
		price: "133.31",
		currency: "EUR",
		countryCode: "NL",
		flag_link: "https://www.countryflags.io/NL/flat/64.png",
		countryName: "Netherlands",
		cases: 1619648,
		contaminationRate: 0.0026,
	},
	{
		destinationIata: "LIS",
		price: "138.74",
		currency: "EUR",
		countryCode: "PT",
		flag_link: "https://www.countryflags.io/PT/flat/64.png",
		countryName: "Portugal",
		cases: 844288,
		contaminationRate: 0.0007,
	},
	{
		destinationIata: "LHR",
		price: "141.00",
		currency: "EUR",
		countryCode: "GB",
		flag_link: "https://www.countryflags.io/GB/flat/64.png",
		countryName: "UK",
		cases: 4457923,
		contaminationRate: 0.0006,
	},
	{
		destinationIata: "MIA",
		price: "322.51",
		currency: "EUR",
		countryCode: "US",
		flag_link: "https://www.countryflags.io/US/flat/64.png",
		countryName: "USA",
		cases: 33088579,
		contaminationRate: 0.0008,
	},
	{
		destinationIata: "DXB",
		price: "325.61",
		currency: "EUR",
		countryCode: "AE",
		flag_link: "https://www.countryflags.io/AE/flat/64.png",
		countryName: "UAE",
		cases: 552920,
		contaminationRate: 0.0027,
	},
	{
		destinationIata: "BKK",
		price: "399.97",
		currency: "EUR",
		countryCode: "TH",
		flag_link: "https://www.countryflags.io/TH/flat/64.png",
		countryName: "Thailand",
		cases: 123066,
		contaminationRate: 0.0291,
	},
	{
		destinationIata: "CMB",
		price: "544.32",
		currency: "EUR",
		countryCode: "LK",
		flag_link: "https://www.countryflags.io/LK/flat/64.png",
		countryName: "Sri Lanka",
		cases: 158333,
		contaminationRate: 0.0229,
	},
	{
		destinationIata: "DPS",
		price: "705.62",
		currency: "EUR",
		countryCode: "ID",
		flag_link: "https://www.countryflags.io/ID/flat/64.png",
		countryName: "Indonesia",
		cases: 1764644,
		contaminationRate: 0.0033,
	},
];

module.exports = results;
